### ISSUE TITLE
Team section : add slider and centre elements

### ISSUE THREAD

**Issue by utk2103** [DevXsphere/Website-devxsphere#39]

**Comment by Musaveershaik** [comment]
Hey, I understand your problem And I would like to contribute to assign me

**Comment by Musaveershaik** [comment]
"I've already centered the elements, but you mentioned adding a slider. Could you please explain more about this? Since there's already a slider, should I customize it to auto-slide or something similar?"


<img width="881" alt="image" src="https://github.com/user-attachments/assets/a4d8b0db-533f-4c9a-8710-50005cb3c1b4">
